"""Run the animation evaluation tree over every v3 cell, as each becomes ready.

The tree is judged by Qwen, generated by Gemini-3.7 (OpenRouter) -- a
deliberately different model family, so the judge is never scoring its own
family's work. It runs from the BARE HOST, not either docker container:

  - img2svg-qwen-venkat serves vLLM on 127.0.0.1:8010 with --network host, so
    its 127.0.0.1 IS the host's. animatebanana-v4
    (which runs the pipeline sweep) is on a bridge network and cannot reach
    that port at all.
  - The animation suite only reads already-exported frames and calls the
    judge -- no LaTeX, no pdftoppm, none of the reasons earlier suites needed
    a container. The host already has openai/PIL/yaml.

"Run everything regardless" (not a gate): animation_quality.run() already
scores every node on every cell and records `would_eliminate` rather than
skipping downstream nodes when an elimination gate fails, so no --stages
restriction is passed here -- every one of the 6 nodes runs on every cell.

Cells are the (style, sample) pairs bench_v3_styles.py already established as
GT-covered (48 of them). This driver does not wait for the whole pipeline
sweep to finish -- it polls each cell's export directory and scores it the
moment frames exist, so scoring runs concurrently with the pipeline sweep
that is still producing the other cells.
"""
from __future__ import annotations

import os
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from img_2_svg_pretraining.pipeline.config import load_config  # noqa: E402
from img_2_svg_pretraining.pipeline.cache import CachePaths  # noqa: E402
from img_2_svg_pretraining.animatebench import results  # noqa: E402

# Overridable so the same driver serves the TikZ and SVG runs:
#   ANIM_CONFIG=bench_v3_or_svg.yaml python scripts/animation_sweep.py
_CFG_NAME = os.environ.get("ANIM_CONFIG", "bench_v3_or.yaml")
CONFIG = REPO / "src/img_2_svg_pretraining/pipeline/configs" / _CFG_NAME
CONFIG_NAME = Path(_CFG_NAME).stem
JUDGE_BACKEND = "qwen_judge"
POLL_S = 20
MAX_WAIT_S = 45 * 60   # give up on a cell that never gets frames after 45min
LOG = REPO / "logs" / "animation_sweep.log"
DATASET = REPO / "data" / "animatebench_v3"
STYLES = ("progressive_reveal", "alpha_masking", "colour_pop",
          "hopping_bounding_box", "sliding_bounding_box")


def _coverage() -> dict[str, list[str]]:
    """style -> sample ids with a reference sequence for it. Same rule as
    scripts/bench_v3_styles.py::coverage, inlined rather than imported so this
    driver has no dependency on scripts/ being an importable package."""
    out: dict[str, list[str]] = {s: [] for s in STYLES}
    for sample in sorted(p for p in DATASET.iterdir() if p.is_dir()):
        for style in STYLES:
            if (sample / "reference" / "seq"
                    / f"{style}_{sample.name}_tikz.json").exists():
                out[style].append(sample.name)
    return out


def log(msg: str) -> None:
    line = f"[{time.strftime('%H:%M:%S')}] {msg}"
    print(line, flush=True)
    with open(LOG, "a", encoding="utf-8") as fh:
        fh.write(line + "\n")


def cells_in_run_order():
    """(style, sample_id) pairs, largest-coverage style first -- matches the
    pipeline driver's own order, so cells become ready roughly in this
    sequence rather than this driver waiting on styles run last."""
    cov = _coverage()
    only = os.environ.get("ANIM_STYLES")
    if only:
        keep = {s.strip() for s in only.split(",") if s.strip()}
        cov = {s: v for s, v in cov.items() if s in keep}
    for style in sorted(cov, key=lambda s: -len(cov[s])):
        for sample_id in cov[style]:
            yield style, sample_id


def exports_ready(cfg, style: str, sample_id: str) -> bool:
    cfg.style = style
    cfg.raw["animation_style"] = style
    paths = CachePaths.from_config(cfg)
    frames_dir = paths.exports(sample_id) / "frames"
    return frames_dir.is_dir() and any(frames_dir.glob("*.png"))


def already_scored(root: Path, style: str, sample_id: str) -> bool:
    path = results.suite_path(root, CONFIG_NAME, style, sample_id, "animation")
    if not path.exists():
        return False
    record = results.read_record(path) or {}
    # A record with only an error (e.g. "no exported frames") is not a score;
    # let it retry once frames actually exist.
    return bool(record.get("stages_run"))


def run_cell(style: str, sample_id: str) -> int:
    cmd = [sys.executable, "-m", "img_2_svg_pretraining.animatebench.run_eval",
           "animation", "--config", str(CONFIG), "--style", style,
           "--only", sample_id, "--judge-backend", JUDGE_BACKEND]
    log(f"  running: {sample_id} / {style}")
    proc = subprocess.run(cmd, cwd=REPO,
                          env={**__import__("os").environ,
                               "PYTHONPATH": str(REPO / "src")},
                          capture_output=True, text=True)
    tail = "\n".join((proc.stdout + proc.stderr).splitlines()[-6:])
    log(f"    exit={proc.returncode}\n    {tail}")
    return proc.returncode


def wait_for_qwen(timeout_s: int = 20 * 60) -> bool:
    import urllib.request
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        try:
            urllib.request.urlopen("http://127.0.0.1:8010/health", timeout=5)
            log("qwen judge: healthy")
            return True
        except Exception:
            time.sleep(10)
    log("qwen judge: never became healthy, giving up")
    return False


def main() -> None:
    LOG.parent.mkdir(parents=True, exist_ok=True)
    log("=== animation sweep start (host-run, judge=qwen_judge)")

    if not wait_for_qwen():
        raise SystemExit(1)

    cfg = load_config(str(CONFIG))
    root = results.evals_root(cfg.cache_root, cfg.dataset_root.name)

    pending = list(cells_in_run_order())
    log(f"{len(pending)} GT-covered cell(s) to score")
    deadlines = {c: time.time() + MAX_WAIT_S for c in pending}
    done, skipped = [], []

    while pending:
        remaining = []
        for style, sample_id in pending:
            cfg_i = load_config(str(CONFIG))  # fresh: cfg.style mutates in place
            if already_scored(root, style, sample_id):
                log(f"  {sample_id} / {style}: already scored, skipping")
                done.append((style, sample_id))
                continue
            if exports_ready(cfg_i, style, sample_id):
                run_cell(style, sample_id)
                done.append((style, sample_id))
                continue
            if time.time() > deadlines[(style, sample_id)]:
                log(f"  {sample_id} / {style}: gave up waiting for frames "
                    f"after {MAX_WAIT_S // 60}min")
                skipped.append((style, sample_id))
                continue
            remaining.append((style, sample_id))
        pending = remaining
        if pending:
            log(f"  {len(pending)} cell(s) still waiting on frames "
                f"({len(done)} done, {len(skipped)} gave up); "
                f"sleeping {POLL_S}s")
            time.sleep(POLL_S)

    log(f"=== done | scored {len(done)}, gave up on {len(skipped)}")
    if skipped:
        log("gave up on: " + ", ".join(f"{s}/{i}" for s, i in skipped))


if __name__ == "__main__":
    main()
