"""Compare two judges' animation-tree scores over the same cells.

The animation suite is judged end to end, so its numbers are only as
trustworthy as the model that produced them. Running the same 29 cells through
two different model families and reading the disagreement is the cheapest check
available -- and a necessary one here, because the animations under test were
generated by Gemini, so a Gemini judge is scoring its own family's work.

What to look for, in order of how much it tells you:

- **The mechanical nodes should agree.** Omission counts and style-compliance
  verdicts come from arithmetic over per-frame reports, not from a model's own
  tally. Wide disagreement there means the plumbing differs, not the opinion.
- **The judged nodes may diverge, and that is the finding.** A large VFS gap is
  a claim about one of the two judges, not about the animation.
- **Coverage first.** A judge that scored fewer timesteps is not a judge that
  scored them lower; `steps` guards against reading a gap that is really an
  outage.

Usage:
    python scripts/compare_judges.py <evals_root_a> <evals_root_b> [label_a label_b]
"""
from __future__ import annotations

import json
import statistics as st
import sys
from pathlib import Path

# (record key, display label, higher-is-better) -- None means "not a score".
METRICS = [
    ("vfs", "VFS (fidelity)", True),
    ("ascs_pass", "ASCS (style)", None),
    ("omission_rate", "Omission rate", False),
    ("element_omission_count", "  elements missed", False),
    ("arrow_omission_count", "  arrows missed", False),
    ("sss", "SSS (selection)", True),
    ("gps", "GPS (pacing)", True),
    ("repetition_rate", "Repetition rate", False),
]
COVERAGE = [("ascs_frames_judged", "ascs"), ("sss_steps_scored", "sss"),
            ("gps_steps_scored", "gps")]


def load(root: Path) -> dict[tuple[str, str], dict]:
    out = {}
    for path in Path(root).glob("*/*/*/animation.json"):
        try:
            out[(path.parent.parent.name, path.parent.name)] = json.loads(
                path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
    return out


def _fmt(v) -> str:
    if v is None:
        return "—"
    if isinstance(v, bool):
        return "pass" if v else "FAIL"
    return f"{v:.3f}" if isinstance(v, float) else str(v)


def main() -> None:
    if len(sys.argv) < 3:
        print(__doc__)
        raise SystemExit(2)
    a_root, b_root = Path(sys.argv[1]), Path(sys.argv[2])
    a_label = sys.argv[3] if len(sys.argv) > 3 else a_root.name
    b_label = sys.argv[4] if len(sys.argv) > 4 else b_root.name

    a, b = load(a_root), load(b_root)
    shared = sorted(set(a) & set(b))
    print(f"{a_label}: {len(a)} cells | {b_label}: {len(b)} cells | "
          f"both: {len(shared)}\n")
    if not shared:
        print("no overlapping cells yet")
        return

    print(f"{'metric':22s} {a_label:>14s} {b_label:>14s} {'Δ':>9s}  {'n':>3s}")
    print("-" * 68)
    for key, label, higher in METRICS:
        av = [a[c].get(key) for c in shared if isinstance(a[c].get(key), (int, float))
              and not isinstance(a[c].get(key), bool)]
        bv = [b[c].get(key) for c in shared if isinstance(b[c].get(key), (int, float))
              and not isinstance(b[c].get(key), bool)]
        if key == "ascs_pass":
            ap = sum(1 for c in shared if a[c].get(key) is True)
            bp = sum(1 for c in shared if b[c].get(key) is True)
            print(f"{label:22s} {f'{ap}/{len(shared)} pass':>14s} "
                  f"{f'{bp}/{len(shared)} pass':>14s} {'':>9s}  {len(shared):>3d}")
            continue
        if not av or not bv:
            print(f"{label:22s} {_fmt(st.mean(av) if av else None):>14s} "
                  f"{_fmt(st.mean(bv) if bv else None):>14s} {'—':>9s}  "
                  f"{max(len(av), len(bv)):>3d}")
            continue
        ma, mb = st.mean(av), st.mean(bv)
        print(f"{label:22s} {ma:>14.3f} {mb:>14.3f} {mb - ma:>+9.3f}  "
              f"{min(len(av), len(bv)):>3d}")

    print("\ncoverage (calls that actually returned a verdict)")
    for key, short in COVERAGE:
        av = sum(a[c].get(key) or 0 for c in shared)
        bv = sum(b[c].get(key) or 0 for c in shared)
        print(f"  {short:5s} {a_label}={av:5d}   {b_label}={bv:5d}")

    # Per-cell agreement on the two nodes that are arithmetic, not opinion.
    agree_ascs = sum(1 for c in shared
                     if a[c].get("ascs_pass") == b[c].get("ascs_pass"))
    agree_om = sum(1 for c in shared
                   if a[c].get("element_omission_count")
                   == b[c].get("element_omission_count"))
    print(f"\nmechanical agreement over {len(shared)} cells:")
    print(f"  style verdict identical   {agree_ascs}/{len(shared)}")
    print(f"  omission count identical  {agree_om}/{len(shared)}")

    widest = sorted(
        (c for c in shared
         if isinstance(a[c].get("vfs"), float) and isinstance(b[c].get("vfs"), float)),
        key=lambda c: -abs(a[c]["vfs"] - b[c]["vfs"]))[:5]
    if widest:
        print("\nwidest VFS disagreements (worth reading the prose for):")
        for c in widest:
            print(f"  {c[0]:22s} {c[1]:22s} "
                  f"{a_label} {a[c]['vfs']:.2f}  vs  {b_label} {b[c]['vfs']:.2f}")


if __name__ == "__main__":
    main()
