"""Generate the eight gemini_ablation_* configs from one baseline.

GENERATED, NOT HAND-WRITTEN. Eight configs differing in one setting each are
guaranteed to drift apart if maintained by hand -- and a drifted knob would be
read as an ablation effect. Edit this script, re-run it, and diff.

THE BASELINE HAS ALL THREE CRITICS ON. The v5 round-one run had them all off
(measured: code_reviewed 24/91, sequence_final 6/91, animation_final 6/91, and
the 91 exports built from raw designer output), so it cannot serve as the
ANIMATEBANANA row of an ablation table whose whole point is removing critics
one at a time. This regenerates that row properly.

EVERY ABLATION GETS ITS OWN cache_root. `CachePaths` derives its lineage from
MODEL names, and all eight configs use google/gemini-3.7-flash for every agent
-- so they would otherwise resolve to one identical lineage and silently
overwrite each other's artifacts. That failure is invisible: the second run
would simply "find" the first run's cached outputs and skip.
"""
from __future__ import annotations

import copy
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
CFG_DIR = REPO / "src/img_2_svg_pretraining/pipeline/configs"
BASE = CFG_DIR / "bench_v5_or_gemini37flash.yaml"
CACHE = "/fsxvision_new/venkat.kesav/img_2_svg_pretraining/data/ablation_cache"

# name -> (human description, mutation applied to the baseline dict)
def _stage1_no_critic(c): c["transmuter"]["diagram_critic"]["enabled"] = False
def _stage2_no_image(c):
    # The parser already sends no image (it is prompt + code only), so this
    # touches the three stage-2 agents that do.
    for a in ("sequencer", "critic", "narrative_writer"):
        c["planner"][a]["send_image"] = False
def _sequencer_no_xml(c): c["planner"]["sequencer"]["send_xml"] = False
def _stage2_no_critic(c): c["planner"]["critic"]["enabled"] = False
def _narration_no_context(c):
    # `image-only-prompt` is selected by the tier, and is exactly the
    # "no paper context" variant.
    c["planner"]["narrative_writer"]["context_tier"] = "image_only"
def _designer_no_image(c): c["animator"]["designer"]["send_image"] = False
def _stage3_no_critic(c): c["animator"]["critic"]["enabled"] = False

ABLATIONS = {
    "full":                  ("ANIMATEBANANA -- full system, all three critics on", None),
    "stage1_no_critic":      ("Stage 1 w/o Critic", _stage1_no_critic),
    "stage2_no_image":       ("Stage 2 w/o Diagram Image Input", _stage2_no_image),
    "sequencer_no_xml":      ("Sequencer w/o XML input", _sequencer_no_xml),
    "stage2_no_critic":      ("Sequencer w/o Critic (Stage 2)", _stage2_no_critic),
    "narration_no_context":  ("Narration Drafter w/o Context", _narration_no_context),
    "designer_no_image":     ("Animation Designer w/o Diagram Image Input", _designer_no_image),
    "stage3_no_critic":      ("Animation Designer w/o Critic (Stage 3)", _stage3_no_critic),
}


def build(name: str, desc: str, mutate) -> dict:
    cfg = yaml.safe_load(BASE.read_text(encoding="utf-8"))
    # The ablation table is about the FULL system, so the baseline turns every
    # critic on; each "w/o critic" ablation then switches exactly one back off.
    cfg["transmuter"]["diagram_critic"]["enabled"] = True
    cfg["planner"]["critic"]["enabled"] = True
    cfg["animator"]["critic"]["enabled"] = True
    cfg["cache_root"] = f"{CACHE}/{name}"
    if mutate:
        mutate(cfg)
    return cfg


HEADER = """# AnimateBanana ablation: {desc}
#
# GENERATED by scripts/make_ablation_configs.py -- edit that, not this file.
#
# Backbone: Gemini 3.7 Flash, identical to bench_v5_or_gemini37flash.yaml in
# every respect except the one ablated setting below (and cache_root).
#
# CACHE IS ISOLATED. All eight ablations run the same model for every agent, so
# they share one CachePaths lineage; without a separate cache_root each would
# silently reuse the previous ablation's artifacts instead of generating its
# own, and the table would show eight copies of one run.
#
# Critics: {critics}
"""


def main() -> None:
    written = []
    for name, (desc, mutate) in ABLATIONS.items():
        cfg = build(name, desc, mutate)
        critics = ", ".join(
            f"{k}={'on' if v else 'OFF'}" for k, v in (
                ("stage1", cfg["transmuter"]["diagram_critic"]["enabled"]),
                ("stage2", cfg["planner"]["critic"]["enabled"]),
                ("stage3", cfg["animator"]["critic"]["enabled"])))
        out = CFG_DIR / f"gemini_ablation_{name}.yaml"
        out.write_text(HEADER.format(desc=desc, critics=critics)
                       + yaml.safe_dump(cfg, sort_keys=False, width=100),
                       encoding="utf-8")
        written.append((out.name, desc, critics))
    for n, d, c in written:
        print(f"  {n:42} {c:38} {d}")
    print(f"\n{len(written)} config(s) written to {CFG_DIR}")


if __name__ == "__main__":
    main()
