#!/usr/bin/env python3
"""Generate the 6 configs: {kimi-k2.6, deepseek-v4-flash-vision} x {193, 216, 91}.

Derived from bench_v5_svg_kimi_k26.yaml, which already has critics DISABLED --
"just regular generation", 6 model calls per cell rather than 13.1.

CACHE SEPARATION IS PER (MODEL, DATASET). `CachePaths` keys artifacts on the
MODEL STRING, so two datasets sharing one cache_root would be fine, but the
91-set is `animatebench_v5` -- the SAME dataset root the ablations use -- and
the ablations already own `ablation_cache/*`. Each config therefore gets its own
cache_root, so no run can find another's artifacts on disk and skip every stage.
"""
from __future__ import annotations
import re, sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CFG = REPO / "src/img_2_svg_pretraining/pipeline/configs"
TPL = CFG / "bench_v5_svg_kimi_k26.yaml"

DATA = REPO / "data"
SETS = {
    "zs":  (DATA / "animatebench_zs",     "zs"),    # 193
    "v6":  (DATA / "animatebench_v6_ds",  "v6"),    # 216
    "abl": (DATA / "animatebench_v5",     "abl"),   # 91
}
MODELS = {
    "kimi_k26": ("moonshotai/Kimi-K2.6", "http://127.0.0.1:8011/v1"),
    "dsv4fv":   ("deepseek-ai/DeepSeek-V4-Flash-Vision-Exp",
                 "http://127.0.0.1:8012/v1"),
}


def main() -> int:
    text = TPL.read_text(encoding="utf-8")
    made = []
    for mkey, (model, base_url) in MODELS.items():
        for skey, (root, tag) in SETS.items():
            out = text
            out = re.sub(r"^  root: .*$", f"  root: {root}", out, flags=re.M)
            out = re.sub(r"^cache_root: .*$",
                         f"cache_root: {DATA}/gen_cache/{mkey}_{tag}", out, flags=re.M)
            # The `served` backend: model string + local port for this model.
            out = re.sub(r"^      base_url: .*$", f"      base_url: {base_url}",
                         out, count=1, flags=re.M)
            out = re.sub(r"^      model: .*$", f"      model: {model}",
                         out, count=1, flags=re.M)
            path = CFG / f"gen_{mkey}_{tag}.yaml"
            header = (
                f"# GENERATED by scripts/make_kimi_ds_configs.py -- edit that, not this.\n"
                f"#   model   {model}\n"
                f"#   dataset {root.name}\n"
                f"#   critics DISABLED (regular generation)\n"
                f"# Per-sample style comes from data/{tag}_style_map.json via the\n"
                f"# runner's --style flag; `animation_style` below is only a default.\n")
            path.write_text(header + out, encoding="utf-8")
            made.append(path.name)
    for m in made:
        print("wrote", m)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
